spring.application.name=prediction

# =====================
# DATABASE
# =====================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================
# JPA
# =====================

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================
# LLM
# =====================

llm.provider=${LLM_PROVIDER}

llm.openai.api-key=${OPENAI_API_KEY}
llm.openai.url=${OPENAI_URL}
llm.openai.model=${OPENAI_MODEL}

llm.deepseek.api-key=${DEEP_SEEK_API_KEY}
llm.deepseek.url=${DEEP_SEEK_URL}
llm.deepseek.model=${DEEP_SEEK_MODEL}
